In [4]:
import pandas as pd

data={'vegetables':['beetroot', 'carrot', 'tomato', 'kovakkai','coconut'],
      'color' : ['purple', 'orange','red','green','white'],
      'unit':['1kg','1kg','1kg','1kg','1piece'],
      'min':[15,25,53,30,'seventeen'],
      'max':[40,45,90,45,38],
     }

In [5]:
market=pd.DataFrame(data)

In [6]:
market

  vegetables   color    unit        min  max
0   beetroot  purple     1kg         15   40
1     carrot  orange     1kg         25   45
2     tomato     red     1kg         53   90
3   kovakkai   green     1kg         30   45
4    coconut   white  1piece  seventeen   38

In [7]:
market.to_csv('market')

In [8]:
market

  vegetables   color    unit        min  max
0   beetroot  purple     1kg         15   40
1     carrot  orange     1kg         25   45
2     tomato     red     1kg         53   90
3   kovakkai   green     1kg         30   45
4    coconut   white  1piece  seventeen   38

In [9]:
pd.read_csv=('market')

In [10]:
market

  vegetables   color    unit        min  max
0   beetroot  purple     1kg         15   40
1     carrot  orange     1kg         25   45
2     tomato     red     1kg         53   90
3   kovakkai   green     1kg         30   45
4    coconut   white  1piece  seventeen   38

In [12]:
market.head(3)  #rows

  vegetables   color unit min  max
0   beetroot  purple  1kg  15   40
1     carrot  orange  1kg  25   45
2     tomato     red  1kg  53   90

In [16]:
market['color'].head(3)   #coloumns

0    purple
1    orange
2       red
Name: color, dtype: object

In [17]:
market[['color','unit']].head(3)

    color unit
0  purple  1kg
1  orange  1kg
2     red  1kg

In [18]:
market.describe()

             max
count   5.000000
mean   51.600000
std    21.686401
min    38.000000
25%    40.000000
50%    45.000000
75%    45.000000
max    90.000000

In [ ]:
market