In [1]:
import pandas as pd
data={'vegetables':['beetroot', 'carrot', 'tomato', 'kovakkai','coconut'],
      'color' : ['purple', 'orange','red','green','white'],
      'unit':['1kg','1kg','1kg','1kg','1piece'],
      'min':[15,25,53,30,'seventeen'],
      'max':[40,45,90,45,38],
     }

In [3]:
market = pd.DataFrame(data)

In [4]:
market

  vegetables   color    unit        min  max
0   beetroot  purple     1kg         15   40
1     carrot  orange     1kg         25   45
2     tomato     red     1kg         53   90
3   kovakkai   green     1kg         30   45
4    coconut   white  1piece  seventeen   38

In [6]:
market.replace('red','black')

  vegetables   color    unit        min  max
0   beetroot  purple     1kg         15   40
1     carrot  orange     1kg         25   45
2     tomato   black     1kg         53   90
3   kovakkai   green     1kg         30   45
4    coconut   white  1piece  seventeen   38